spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://localhost:3306/splitpay-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: never